service: summon-api

provider:
    name: aws
    runtime: nodejs12.x
    region: eu-central-1

# functions
functions:
    serverHealthCheckGet:
        handler: source/functions/serverHealthCheckGet.handler
        events: # The events that trigger this function
            - http:
                  path: api/ping
                  method: get
    serverHealthCheckPost:
        handler: source/functions/serverHealthCheckPost.handler
        events: # The events that trigger this function
            - http:
                  path: api/ping
                  method: post

# Serverless plugins
plugins:
    - serverless-plugin-typescript

# Resources your functions use
resources:
