app: summon-api
service: summon-api

provider:
    name: aws
    runtime: nodejs12.x
    region: eu-central-1

# functions
functions:
    slackEvents:
        handler: source/functions/slack/eventsRoute.handler
        # self:custom.stage allows us to know what stage we are in to load correct file
        # environment: ${file(./${self:custom.stage}.env.json)}
        events: # The events that trigger this function
            - http:
                  path: api/slack/events
                  method: post
    serverHealthCheckGet:
        handler: source/functions/utils/server-health-check/serverHealthCheckGet.handler
        events: # The events that trigger this function
            - http:
                  path: api/ping
                  method: get
    serverHealthCheckPost:
        handler: source/functions/utils/server-health-check/serverHealthCheckPost.handler
        events: # The events that trigger this function
            - http:
                  path: api/ping
                  method: post

custom:
    # stage tells if we are in dev, prod or other stage. It is based on -s flag value
    # when deploying serverless. For example, serverless deploy -s dev would make stage: dev
    stage: ${opt:stage}
    datadog:
        addExtension: true
        apiKey: ffs

# Serverless plugins
plugins:
    - serverless-plugin-typescript
    - serverless-offline
    - serverless-plugin-datadog

# Resources your functions use
resources:
