# .github/workflows/main.yaml
name: Deploy to main branch

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                node-version: [^14.15.0]
                # Set N number of parallel jobs you want to run tests on.
                # Use higher number if you have slow tests to split them on more parallel jobs.
                # Remember to update ci_node_index below to 0..N-1
                ci_node_total: [4]
                # set N-1 indexes for parallel jobs
                # When you run 2 parallel jobs then first job will have index 0, the second job will have index 1 etc
                ci_node_index: [0, 3]

        steps:
            - uses: actions/checkout@v1

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: yarn install
              run: |
                  yarn install
            - name: Run tests with Knapsack Pro
              env:
                  KNAPSACK_PRO_TEST_FILE_PATTERN: '{tests/**/*.test.ts}'
                  KNAPSACK_PRO_TEST_SUITE_TOKEN_JEST: ${{ secrets.KNAPSACK_PRO_TEST_SUITE_TOKEN_JEST }}
                  KNAPSACK_PRO_CI_NODE_TOTAL: ${{ matrix.ci_node_total }}
                  KNAPSACK_PRO_CI_NODE_INDEX: ${{ matrix.ci_node_index }}
              run: |
                  $(npm bin)/knapsack-pro-jest
